# Generated by Django 5.0.2 on 2024-02-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("entrega", models.DateTimeField()),
                ("terminada_em", models.DateTimeField(null=True)),
            ],
        ),
    ]
