# Generated by Django 5.0.2 on 2024-02-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="criado_em",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="entrega",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="terminada_em",
            field=models.DateField(blank=True, null=True),
        ),
    ]
